server {
    listen 127.0.0.1:8332;
    server_name blocknet-daemon-local;

    access_log off;

    location / {
        include /etc/nginx/blocknet-daemon-active-upstream.inc;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }
}
