[package]
name = "pool-common"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
blocknet-pow-kernel.workspace = true
bs58.workspace = true
libc.workspace = true
curve25519-dalek.workspace = true
chrono.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
sha3.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
argon2.workspace = true
