[Service]
ExecStart=
ExecStart=/usr/bin/prometheus-alertmanager \
  --config.file=/etc/alertmanager/alertmanager.yml \
  --storage.path=/var/lib/prometheus/alertmanager \
  --cluster.listen-address= \
  --web.listen-address=127.0.0.1:9093
